using Test

@testset "Odin.jl" begin
    include("dsl/test_parse.jl")
    include("dsl/test_classify.jl")
    include("dsl/test_codegen.jl")
    include("dsl/test_arrays.jl")
    include("dsl/test_output.jl")
    include("dsl/test_interpolation.jl")
    include("dsl/test_odin_model.jl")
    include("dsl/test_additional_models.jl")
    include("dsl/test_school_closure.jl")
    include("dsl/test_yellowfever.jl")
    include("dsl/test_yf_delay.jl")
    include("dsl/test_yf_vtrack.jl")
    include("dsl/test_beta_blocks.jl")
    include("dsl/test_orov.jl")
    include("dsl/test_fitting_workflow.jl")
    include("dust/test_system.jl")
    include("dust/test_simulate.jl")
    include("dust/test_sdirk.jl")
    include("dust/test_events.jl")
    include("dust/test_filter.jl")
    include("dust/test_sensitivity.jl")
    include("monty/test_packer.jl")
    include("monty/test_model.jl")
    include("monty/test_samplers.jl")
    include("monty/test_new_samplers.jl")
    include("monty/test_sample.jl")
    include("monty/test_dsl.jl")
    include("monty/test_turing_bridge.jl")
    include("categorical/test_categorical.jl")
    include("categorical/test_categorical_advanced.jl")
    include("gpu/test_gpu.jl")
end
